{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7312746"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.0.0.aar",
          "url": "camera-camera2-1.0.0.aar",
          "size": 284380,
          "sha512": "3564310de4d70e0795c06abf3c8a695a27f6212b13a5cbfbfae5ee388f5c7c3412befe8ffbe3e27c3400c289bc765308402c795424672a939c9614d69dd1dae8",
          "sha256": "5da2221587bc4cd78cafdf790c08eda781b08bcd3b815153a9d1b3b41f1825d5",
          "sha1": "403e4dabfcf607adfaa935f734f29603ad148238",
          "md5": "21907977d40458bf24df96e3241e4c04"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.0.0.aar",
          "url": "camera-camera2-1.0.0.aar",
          "size": 284380,
          "sha512": "3564310de4d70e0795c06abf3c8a695a27f6212b13a5cbfbfae5ee388f5c7c3412befe8ffbe3e27c3400c289bc765308402c795424672a939c9614d69dd1dae8",
          "sha256": "5da2221587bc4cd78cafdf790c08eda781b08bcd3b815153a9d1b3b41f1825d5",
          "sha1": "403e4dabfcf607adfaa935f734f29603ad148238",
          "md5": "21907977d40458bf24df96e3241e4c04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-1.0.0-sources.jar",
          "url": "camera-camera2-1.0.0-sources.jar",
          "size": 206903,
          "sha512": "b07d729c48cb34a6faa47338e0f70248695e4692d3b53054bf58f4819631dacbc0a4d7de1ae526caf37bc60c6b3ce6ce1afd73f14774fb08a9fde838b4bde30b",
          "sha256": "80152794b1d8c75bfba2446997ed756f0faa57c2cf5dbf8dff8b850931905a00",
          "sha1": "7b4a9e8ca316b8296d06ad7b887348217f9beb8b",
          "md5": "26530b45d27d9b759568f487c8561ad3"
        }
      ]
    }
  ]
}
