{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7312746"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.0.0.aar",
          "url": "camera-core-1.0.0.aar",
          "size": 470791,
          "sha512": "112b661ff8deba01684878d14028a0afa20fc6fc8f36bfc3d0ad5247f3362affa0f234de2ccbb0c7e9b3826698180581c7822b5b62fb24c9987f0eaba0818dde",
          "sha256": "8ed585b9227d0b29904c771a427aeaf72b54bbf5aecfb4f70d58cdde2e3b6f81",
          "sha1": "d65152ad47da5dafc3576f36f964ae2567156bda",
          "md5": "6f00f523b01b152104a0c85b1549eeca"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.0.0.aar",
          "url": "camera-core-1.0.0.aar",
          "size": 470791,
          "sha512": "112b661ff8deba01684878d14028a0afa20fc6fc8f36bfc3d0ad5247f3362affa0f234de2ccbb0c7e9b3826698180581c7822b5b62fb24c9987f0eaba0818dde",
          "sha256": "8ed585b9227d0b29904c771a427aeaf72b54bbf5aecfb4f70d58cdde2e3b6f81",
          "sha1": "d65152ad47da5dafc3576f36f964ae2567156bda",
          "md5": "6f00f523b01b152104a0c85b1549eeca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-core-1.0.0-sources.jar",
          "url": "camera-core-1.0.0-sources.jar",
          "size": 371990,
          "sha512": "0a4e9ffbf3ab25f23f820d5020ba32dddcc9d0b9357b2073858cfe8ccdca6f84c5d90515e6724fda5a9cefa0aa91f7888a922567cc093683283b572fdbbe7cd0",
          "sha256": "9eeb174b41362a1e23bdd1de4667f26ce34ee44317aad6b48497da22e0603979",
          "sha1": "4fbad1718d3771868194b1646c9397e9a3401714",
          "md5": "0c2acd60b83f7dcb02888c36a34714ee"
        }
      ]
    }
  ]
}
