{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7215933"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.2.2.aar",
          "url": "activity-1.2.2.aar",
          "size": 67536,
          "sha512": "938eb426c1210c910a03d172a5f272097b415fa8d32b90fbf1a66701fa488d178f1d975dd0809453c60edb1839767e78203cb7633a0cff904e983123d7807276",
          "sha256": "e165fb20f006b77894d349572cc3acd2760baa8416ae4d33cb8de6a84dd6730c",
          "sha1": "8c5d9ba698358f8e40f70e3c144b9484290a4f71",
          "md5": "0ce57744d5ea1d57dd9ac420d1e54a10"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.2.2.aar",
          "url": "activity-1.2.2.aar",
          "size": 67536,
          "sha512": "938eb426c1210c910a03d172a5f272097b415fa8d32b90fbf1a66701fa488d178f1d975dd0809453c60edb1839767e78203cb7633a0cff904e983123d7807276",
          "sha256": "e165fb20f006b77894d349572cc3acd2760baa8416ae4d33cb8de6a84dd6730c",
          "sha1": "8c5d9ba698358f8e40f70e3c144b9484290a4f71",
          "md5": "0ce57744d5ea1d57dd9ac420d1e54a10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.2.2-sources.jar",
          "url": "activity-1.2.2-sources.jar",
          "size": 35503,
          "sha512": "f326f014f24a774e42ab0034be97369829e6c57c2d170c1b3bcd114541b38388bf8f59cd6bc967bdf61f594b5310b29561404ba3b09700b744063cba0379a954",
          "sha256": "90974d9e66d439998549aeaf2f2aab7a6ab24f453cfcb39c184d3888a6a0a545",
          "sha1": "90a39fdeb6c8aa134518e9fc089fd2625a0329b0",
          "md5": "c2137b6b05a66e313743784448c25e06"
        }
      ]
    }
  ]
}
